---
- name: Provision PostgreSQL for Zabbix
  hosts: zabbix_databases
  become: true
  roles:
    - postgresql

- name: Provision Zabbix servers
  hosts: zabbix_servers
  become: true
  roles:
    - zabbix_server

- name: Provision Zabbix proxies
  hosts: zabbix_proxies
  become: true
  roles:
    - zabbix_proxy

- name: Provision Zabbix frontends
  hosts: zabbix_frontends
  become: true
  roles:
    - zabbix_frontend

- name: Provision Zabbix agents
  hosts: zabbix_agents
  become: true
  roles:
    - zabbix_agent
